### ISSUE TITLE
机载mini PC使用sdk v3.3例程使用不正常

### ISSUE THREAD

**Issue by YJ-L-2017** [unitreerobotics/unitree_legged_sdk#11]
在机载mini PC上使用sdk v3.3例程,sport_v1.19。example_walk例程可以正常工作，运行example_dance例程时出现错误 Lock memory failed,
![image](https://user-images.githubusercontent.com/32069254/138794796-cb766168-85dc-4f5e-802e-24bdc9d0085d.png)

**Comment by TrivasZhang** [comment]
Feel free to reopen it.
