### ISSUE TITLE
robot_interface.so: undefined symbol: PyInstanceMethod_Type  

### ISSUE THREAD

**Issue by Liu-Xiaoyan97** [unitreerobotics/unitree_legged_sdk#125]
Now I am trying to run example_walk.py, but I got the ImportError that 'robot_interface.so: undefined symbol: PyInstanceMethod_Type '.  I confirm that I have compiled the relevant files successfully and have robot_interface.cpython-38-x86_64-linux-gnu.so (python3.6 for aarch64 used) in lib/python/amd64 and arm64. And I renamed the file in arm64 to robot_interface.so and put it in the same directory as example_walk.py. Anyone can help me? @k-okada @sktometometo @holiray @matheecs @OnlineMC 
![WechatIMG5](https://github.com/unitreerobotics/unitree_legged_sdk/assets/113759181/1b3664ce-b3d9-4f52-8209-4d50bab4814d)

**Comment by UnInterstedLedge** [comment]
have you been able to figure this out?

**Comment by Liu-Xiaoyan97** [comment]
> have you been able to figure this out?

I recommend recompiling with the version of python you're using, which will solve most of the problems. This problem has been solved, but the specific solution, I can't remember, should be to recompile.

**Comment by Liu-Xiaoyan97** [comment]
Issue has been solved.

**Comment by UnInterstedLedge** [comment]
i got the example_walk.cpp to work instead. so it's fine now.
