### ISSUE TITLE
SendHighROS.pitch not work well

### ISSUE THREAD

**Issue by quannguyen123456** [unitreerobotics/unitree_legged_sdk#14]
I try to control A1 by raspberry Pi4 , make robot swing by SendHighROS.pitch command, change from -1 to 1, but robot head always turn down, the hip is higher. And can not control by angle from -20 ~ 20 degrees. 
Does anyone know reason why? please Help me.

Thank you.

**Comment by TrivasZhang** [comment]
Feel free to reopen it.
