### ISSUE TITLE
send high-level commands (walk), and receive low-level sensor readings

### ISSUE THREAD

**Issue by talhen123** [unitreerobotics/unitree_legged_sdk#15]
Hello, I purchased A1 a few months ago for academic research on Estimation. To do this, I need to send high-level commands (walk), and receive low-level sensor readings (for the Estimation). How can this be done? 
I can not do that under the same portal. Is it possible to work with two portals at the same time?

**Comment by TrivasZhang** [comment]
When under high-level control, I'm trying to return low-level date.
Did joint position enough? Will the odometry estimator need joint velocity or others?

**Comment by itaouil** [comment]
Hi @TrivasZhang,

If you could include the whole **MotorState.msg** in the **HighState.msg** would be great.

Because for publishing the TF tree I require the joint positions, their velocity and the estimated torque for every single servo.

**Comment by evyatarluv** [comment]
Hi @TrivasZhang ,

Can you also add the motor state to sdk v3.3 for A1?

**Comment by talhen123** [comment]
Hi @TrivasZhang ,
For the odometry estimator I will need the unfilter(raw) joints position, speed, and torques.
If it is possible to add for SDK 3.3 (I use unitree A1) the whole **MotorState** it would be great and Easier.
tanks!

**Comment by TrivasZhang** [comment]
> Hi @TrivasZhang ,
> 
> Can you also add the motor state to sdk v3.3 for A1?

Maybe later for A1 sport mode update. And after this update, some other functions, like vision following will not take effect, only sport mode works. 
Will that ok?

**Comment by TrivasZhang** [comment]
Hi @talhen123 
I couldn't get the point why need **raw** date for  joints position, speed, and torques. 
That will change the whole communication related codes and seems take little effect.

**Comment by talhen123** [comment]
Hi @TrivasZhang 
I need the raw data only for the joints position and velocity to calculate the measurement noise for the kalman filter

**Comment by evyatarluv** [comment]
Hi @TrivasZhang

There are some bugs with v3.3.3 on A1 When I'm trying to run the example_walk the robot doesn't move and the observations are {0}.
The same exmaple with v3.2 work fine.

**Comment by TrivasZhang** [comment]
@evyatarluv 
Have you upgrade the A1_sport version to >=1.20?

**Comment by TrivasZhang** [comment]
@talhen123 
Sorry for the raw data, can't be trans now.

**Comment by evyatarluv** [comment]
> @evyatarluv Have you upgrade the A1_sport version to >=1.20?

I'm not sure about that.. how can I upgrade the A1_sport version?

**Comment by TrivasZhang** [comment]
Ask our sales team for upgrade issue.

**Comment by talhen123** [comment]
> @talhen123 Sorry for the raw data, can't be trans now.

That's fine, we're doing the project together

**Comment by itaouil** [comment]
@TrivasZhang 

I saw that the 3.3.3 release was only targeted to the A1 robot and not the Aliengo.

Would it be possible to extend it also to the Aliengo robot, as that is the one that I have.

Sorry for not noticing that it was only for A1 from an early start.

**Comment by TrivasZhang** [comment]
@itaouil 
Please wait for the next version of Aliengo sport mode. I will notice my colleague to keep up.

**Comment by Lior-Falach** [comment]
@TrivasZhang 

Many thanks for the support.
Using the 3.3.3 SDK with the A_Sport 1.20 I can operate the low level example such as position and velocity and get the motorstate feedback, however, the highllevel example, e.g. example_walk  seems to be doing noting, no commands sent to the robot anf no feedback returns.
Would greatly appreciate any help on the subject.

Lior

**Comment by TrivasZhang** [comment]
File example_walk, line16
`udp(8090, "192.168.123.11", 8082 ...)` needs change to `udp(8090, "192.168.123.161", 8082 ...)`
I should update this release to prevent confusion.

**Comment by Lior-Falach** [comment]
@TrivasZhang 
the current command is udp(8090, "192.168.123.161", 8082 ...), anyway, I tried both i.p. and non of them worked...

**Comment by littleggghost** [comment]
@Lior-Falach 
Have you rebuild the project after modify the codes?

**Comment by Lior-Falach** [comment]
@littleggghost 
Sure, rebuild and added (uncommented ) a print motorstate command.

**Comment by TrivasZhang** [comment]
I retest it without error. Did you forget to reboot the robot after upgrade?
Or, maybe try this [https://github.com/unitreerobotics/unitree_legged_sdk/releases/tag/3.3.4](url)

**Comment by Lior-Falach** [comment]
@littleggghost @TrivasZhang 
Tried both 3.3.3 and 3.3.4 SDK version, all work in Low State yet both do not work in High State.
I returned to old version 3.2 and High State examples work.
A_Sport version is 1.20
Would greatly appreciate your support.

Lior

**Comment by TrivasZhang** [comment]
I doubt if you have upgraded the A1_sport correctly. Could you paste a screenshot of the `/home/unitree` folder?

**Comment by itaouil** [comment]
> @itaouil Caused by the sdk needs sport mode support the interface, please wait for the next version of Aliengo sport mode. I will notice my colleague to keep up.

Hi @TrivasZhang,

Any update on when will the AlienGo sport mode be available so as to obtain low sensor readings while in high level mode also for AlienGo?

**Comment by TextZip** [comment]
Hi @TrivasZhang , I do not think AlienGo still supports the reading of Motor States during High-Level Command. Can this please be added? 

@itaouil were you able to find some fix for this?

**Comment by heartInsert** [comment]
guys ,  do  you  know  how to get  ` /gazebo/model_states `  and  `/aliengo_gazebo/joint_states`    in  a  real  robot ?  I   have  run   successfully in  Gazebo , but  I  am  stuck   in    how  to   run    subscribe  or  publish  these  in  a  real  robot .
