### ISSUE TITLE
AlienGo机载minpc上运行自带的sdk无反应。

### ISSUE THREAD

**Issue by LinkZelad** [unitreerobotics/unitree_legged_sdk#16]
您好，我购买了aliengo，使用手柄可以正常操作，而进入机载minpc里运行里面的unitree_legged_sdk的example，例如sudo ./example_walk_aliengo,能正常打印出信息无报错，但狗子并没有任何动作~请问是哪里有问题呢？

**Comment by TrivasZhang** [comment]
About usage, please contact our sales team for detailed support.
