### ISSUE TITLE
GO1在ROS中获取摄像头以及其他传感器数据

### ISSUE THREAD

**Issue by trebladev** [unitreerobotics/unitree_legged_sdk#18]
你好，我前一段时间购买了GO1，我想在ros中获得摄像头以及其他传感器的数据，请问会可以在sdk中取得这些数据吗？谢谢

**Comment by Zhaiweiwei0** [comment]
We will soon be uploading the SDK for image datas transfer. For other sensor datas, you can refer to unitree_legged_sdk/include/unitree_legged_sdk/comm.h.

**Comment by trebladev** [comment]
谢谢，期待接下来的视觉sdk

**Comment by Zhaiweiwei0** [comment]
> 谢谢，期待接下来的视觉sdk

https://github.com/unitreerobotics/UnitreecameraSDK
