### ISSUE TITLE
Request binary library compiled for Mac M1 arm

### ISSUE THREAD

**Issue by erwincoumans** [unitreerobotics/unitree_legged_sdk#2]
The new Apple Mac Mini with arm64 CPU is an attractive platform for onboard compute: it is very fast (often faster than high-end AMD Ryzen and Intel) and low-power.

I confirmed that the power usage is 0.26A idle, and stays well below 2A (typically 0.5A), so the 12V connector on A1 can be used. It is possible to install a Linux virtual machine (I will try), but it is nicer to use Mac OSX native arm code instead.

Would it be possible to recompile this library for this platform?

**Comment by Zhaiweiwei0** [comment]
Hello, we haven't done any tests for this platform yet, Thank you for your suggestion!

**Comment by TrivasZhang** [comment]
yxyang told me he solved it in another way, so I close this issue.
Feel free to reopen it if needed.

**Comment by Marco-Delgado** [comment]
> yxyang told me he solved it in another way, so I close this issue. Feel free to reopen it if needed.

Is there any resource on how to compile the legged sdk for m1 macs? I'm attempting to work through it now however I am at a roadblock and unsure how to bypass it.
