### ISSUE TITLE
Motor substitution: is there any specific software to run for calibration/connection?

### ISSUE THREAD

**Issue by luigicampanaro** [unitreerobotics/unitree_legged_sdk#22]
Hi,

we recently substituted the original motor provided with the robot with a spare one.

The new motor receives power, but logging the position we got zeros: is there any **specific software** we have to run for calibration/connection? Or is there a detailed guide to follow when a motor is substituted?

Thank you in advance for helping! :)

**Comment by littleggghost** [comment]
Sure, this needs some steps to recalibrate the joint position. Please contact our sales team for detailed support.

**Comment by TrivasZhang** [comment]
Sure, this needs some steps to recalibrate the joint position. Please contact our sales team for detailed support.
