### ISSUE TITLE
Wrong values returned when receiving high state

### ISSUE THREAD

**Issue by itaouil** [unitreerobotics/unitree_legged_sdk#23]
Hi,

I tried the SDK version 3.3 and 3.3.1 in order to command with high level commands and receive the respective high state for the AlienGo robot, but with both SDKs, and all the examples I tried (example_walk.cpp, lcm_server_high.cpp) the logged high state attributes are completely wrong.

In the example below I printed the velocities (while the robot was standing and therefore not moving) and the velocities returned are not correct. And this is the same for all attributes.

![Screenshot 2022-02-14 11:10:33](https://user-images.githubusercontent.com/17275225/153844033-d7aaad44-20ab-4fbf-8b35-975d95f0b5ac.png)

Any idea why this would be?

**Comment by TrivasZhang** [comment]
That's because the sportMode on Aliengo is fall behind SDK-v3.3. We will fix it next few days.

**Comment by TrivasZhang** [comment]
That will  catch up with SDK-v3.4.2

**Comment by itaouil** [comment]
Ok, thanks!

I will keep an eye for the release in the next few days.

**Comment by itaouil** [comment]
Any update on when the new SDK is going to be released?

This month or most likely next month? So that I can plan the next steps for the project I am working on.

Thanks :)

**Comment by TrivasZhang** [comment]
Sorry for my late response.
I promise before this week Saturday.

**Comment by itaouil** [comment]
Ok thanks.

**Comment by jorgef1299** [comment]
Hi @TrivasZhang @itaouil!

I'm now starting to work with the AlienGO robot, and I do not understand which is the best SDK release to use. Should I use v3.3.1 as suggested in the README, or should I go for v3.4.2 instead?

Also, do I have to update the robot's firmware? Sport mode? How can I do that?

Thanks.

**Comment by itaouil** [comment]
Hi @jorgef1299,

I guess it depends on whether your AlienGo robot was delivered with the updated sport mode firmware or not (a way to check is to see if you can activate sport mode and the respective stair mode climbing locomotions -> https://www.roscomponents.com/en/index.php?controller=attachment&id_attachment=506)

If you can activate the above locomotions, which means you have your firmware updated already, then you will have to wait for a new release of 3.4.2 which @TrivasZhang  is working on, but I am not sure when it will be released.

If you can't activate them, which means you don't have a firmware update and that your robot cannot tackle uneven terrains, you can use SDK 3.2 I think (this is the one I was using before the firmware update).

In order to update the firmware you have to contact the sales team and ask, but @TrivasZhang can correct me if I am wrong.

I hope this helps!

**Comment by TrivasZhang** [comment]
Sorry for my late reply.
You can now ask our support team for Aliengo-sportMode-v1.0.18 and related sdk. This version has a shorter motorState than SDK v3.4.2 in HIGHLEVEL control.
Though we plan to support SDK v3.4.2, but met some old version issue. So please use this version for your need now.

**Comment by TrivasZhang** [comment]
> 

Sure

**Comment by TrivasZhang** [comment]
> So if I ask the support team for **Aliengo-sportMode-v1.0.18 and related sdk** I will be able to command the robot and receive high state information?

Sure

**Comment by TrivasZhang** [comment]
Please notice me if meet problems.

**Comment by itaouil** [comment]
> Please notice me if meet problems.

I will email the support team now and will keep you updated.

**Comment by jorgef1299** [comment]
Thank you both for your replies.
So, if I use the **Aliengo-sportMode-v1.0.18** version will I be able to activate the new sport 3.0 mode and handle uneven terrains?

**Comment by itaouil** [comment]
Yes.

You can contact their support team (https://www.unitree.com/booking) and they will send you the sport mode and respective SDK. But I think this is only in the case where you already have the robot with the firmware updated (i.e. you can tackle uneven terrains with it right now). If not, then they will have to send you some USB sticks to do the firmware update first (this was at least my case as the robot I have was not updated to turn on sport mode 3.0 back then)

**Comment by jorgef1299** [comment]
Ok. I thought that using this new firmware would also add sport mode 3.0. 

I will contact the support line for more information...
Thank you

**Comment by itaouil** [comment]
OK, problem solved.

Thanks :).

**Comment by itaouil** [comment]
Hi @TrivasZhang 

I noticed that you introduced the **MotorStateLight** in the high state , but the values are all 0 (all the other values are correct). Would it be possible to obtain the actual values of the motors?

**Comment by TrivasZhang** [comment]
Did the Aliengo-sportMode-v1.0.18 runs?

**Comment by itaouil** [comment]
Yes sport mode 1.0.18 runs.

**Comment by TrivasZhang** [comment]
But our support team test today and motor data seems fine. Would you contact support@unitree.cc for more details?

**Comment by itaouil** [comment]
Thanks for testing it out again.

It turns out it was my mistake. Now I also receive the light motor state values.
