### ISSUE TITLE
how to solve this problem 

### ISSUE THREAD

**Issue by ROK-KJ** [unitreerobotics/unitree_legged_sdk#25]
hello everyone.

when i run the ./udp_send_test

this error is emerged.

itree_legged_sdk/build# ./udp_send_test 
UDP Initialized. Port: 8017 
[Loop Start] named: udp_send, period: 9(ms), run at cpu: 3 
[Loop Start] named: udp_recv, period: 9(ms), run at cpu: 3 
**[Loop Start] named: calc_loop, period: 9(ms), cpu unspecified**

what is the cpu unspecified ?

How could i solve this problem.

please help me.
Thanks.

**Comment by TrivasZhang** [comment]
```
    LoopFunc loop_control("control_loop", custom.dt,    boost::bind(&Custom::RobotControl, &custom));
    LoopFunc loop_udpSend("udp_send",     custom.dt, 3, boost::bind(&Custom::UDPSend,      &custom));
```
The LoopFunc constructor function is overloading. The third parameter means which cpu will run this thread.
 And cpu unspecified is not an error, the cpu will be  assigned by system.
