### ISSUE TITLE
udp.GetRecv didn't work!

### ISSUE THREAD

**Issue by wantsu** [unitreerobotics/unitree_legged_sdk#3]
I ran the `multi_pc_udp_recv.cpp` in examples for accessing the msg that feed back from server, however, after excecuting the line `udp.GetRecv((char*)&a);` the recieved data ` printf("%d\n", a.direction);` is always emptry; I've try to access other data like `HighState`, still same. 

Please give me some guidances of how to obtain the robot's state information (e.g. linear velocity, angular velocity ) though this sdk or any other ways. Thanks!

**Comment by TrivasZhang** [comment]
_multi_pc__ related files are just as an example udp usage between different IP/port. If data is empty, please check your IP/port.
If your robot works fine, then the state will not empty. If there has problem with your robot, please contact our support team support@unitree.cc

**Comment by TrivasZhang** [comment]
_multi_pc__ related files are just as an example udp usage between different IP/port. If data is empty, please check your IP/port.
If your robot works fine, then the state will not empty. If there has problem with your robot, please contact our support team support@unitree.cc
