### ISSUE TITLE
SDK data at 1KHz

### ISSUE THREAD

**Issue by itaouil** [unitreerobotics/unitree_legged_sdk#32]
Hi,

I would like to ask if it is possible to obtain the data from the SDK at a higher frequency than the 500Hz which is at the moment? And if yes if this would add computational burden or not?

Best,
Ilyass

**Comment by TrivasZhang** [comment]
If an Aliengo can run the sport mode process, then the max communication frequency is 1Khz.
All A1 and Go1 support 1Khz communication frequency.
