### ISSUE TITLE
In high-level mode , cmd.mode 2 does not work when set cmd.mode 0

### ISSUE THREAD

**Issue by HBSIM0** [unitreerobotics/unitree_legged_sdk#35]
Hello Unitree

I am implementing a moving robot using example_walk.cpp.
The code  below does not work.
I want to make the robot stop and move again.

 **//Works well**
if(motiontime > 14000 && motiontime < 18000){
        cmd.mode = 2;
        cmd.gaitType = 1;
        cmd.velocity[0] = 0.1f; // -1  ~ +1
        //cmd.yawSpeed = 2;
        //cmd.footRaiseHeight = 0.1;
        // printf("walk\n");
    }

   **//Works well**
    if(motiontime > 18000 && motiontime < 20000){
        cmd.mode = 0;
        cmd.velocity[0] = 0;
    }

  **//Not working here**
    if(motiontime > 20000 && motiontime < 24000){
        cmd.mode = 2;
        cmd.gaitType = 1;
        cmd.velocity[0] = 0.1f; // -1  ~ +1
        //cmd.bodyHeight = 0.1;
        // printf("walk\n");
    }

robot :  Go1 Edu
sdk version : v3.5.1
Sport mode : 1.37.0
hardware : 0.1.9
firmware : 0.1.37

**Comment by jjq556** [comment]
Hi, sorry for the inconvenience brought to for. You need to change the"0.1" in the  cmd.velocity[0] = 0.1f; // -1 ~ +1 into a bit larger number such as 0.2. The explaination of  -1 ~ +1 is a wrong version,pls ignore it. If you still have some questions,pls let me know.

**Comment by HBSIM0** [comment]
It's very simple
Thanks
