### ISSUE TITLE
Accurate yaw for A1

### ISSUE THREAD

**Issue by pab47** [unitreerobotics/unitree_legged_sdk#38]
The yaw angle on A1 drifts when the robot is standing still. This could be fixed using magnetometer values. By any chance the IMU on-board the A1 have a magnetometer? If yes, can you provide magnetometer readings in the SDK?

**Comment by TrivasZhang** [comment]
We use 6-DOF imu rather than 9-DOF. The motors in trunk will has much interference to magnetometer.
So the yaw drifts.
