### ISSUE TITLE
Sometimes the Go1 app BMS information is not visible.

### ISSUE THREAD

**Issue by HBSIM0** [unitreerobotics/unitree_legged_sdk#39]
Sometimes Go1 App BMS information is not visible.
At this time, I checked the SDK's GetRecv (HighState) and found that all the BmsState values are zero.

![Screenshot_20220602-091018_Go 1](https://user-images.githubusercontent.com/97996197/171523833-d9bc08f9-0562-430e-bbae-eb5bafc4680e.jpg)

![Screenshot_20220602-091029_Go 1](https://user-images.githubusercontent.com/97996197/171523859-d9335386-ccf2-4bff-8ace-7b20f65d5c16.jpg)

**Comment by TrivasZhang** [comment]
Did this bms information works at some times, or it always nothing?

**Comment by HBSIM0** [comment]
It happens sometimes

**Comment by TrivasZhang** [comment]
If sport mode process (Legged_sport) is killed or quit, then the information is unavaliable, until this process rerun again.

**Comment by HBSIM0** [comment]
How do I check if the sport mode process is alive?

If BMS is not available, BMS information is not available even if the robot reboots and waits for more than 3 minutes. 
When the battery is fully charged, BMS information is available.

**Comment by TrivasZhang** [comment]
Next time if the BMS info missing, then you can do the low-level control to print the bms state.
This will locate the problem.

**Comment by HBSIM0** [comment]
I don't think I can solve the zero on the app.

**Comment by TrivasZhang** [comment]
I need find out this problem happens at high mode or low mode, so when informations gone next time, exit sport mode and use low mode to print. If low mode works then it's high mode problem.

**Comment by MAVProxyUser** [comment]
This is the same issue I mailed support about a month or so ago. I was told it was a known bug. I am on a MAX model, which I understand is basically a pro with a 4g modem, so I am unable to move to low-level as suggested above. My BMS output has been steady broken for months on end.

**Comment by maggusscheppi** [comment]
This issue seems to have a root cause in the electronic on the battery. You can read out values from battery via usb-c with 921kbit on the charging station. With a defect battery you receive no values.
