### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by JetBelson** [unitreerobotics/unitree_legged_sdk#40]
PC OS: Ubuntu20.04.

SDK Version 3.5.1

After following the instructions from the manual, all dependencies were installed successfully, and the ping operation works. But the SDK installation has the below error.

Any suggestion?

_/usr/bin/ld: skipping incompatible /home/XXX/software/unitree_legged_sdk/lib/libunitree_legged_sdk_arm64.so when searching for -lunitree_legged_sdk_arm64
/usr/bin/ld: cannot find -lunitree_legged_sdk_arm64
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/lcm_server.dir/build.make:84: lcm_server] Error 1
make[1]: *** [CMakeFiles/Makefile2:90: CMakeFiles/lcm_server.dir/all] Error 2
make: *** [Makefile:84: all] Error 2_

**Comment by JetBelson** [comment]
SDK Version 3.5.1

**Comment by HKU-CICID** [comment]
the error is due to the link library, need to match it with your machine by choosing libunitree_legged_sdk_arm64 or libunitree_legged_sdk_amd64.

**Comment by pab47** [comment]
Try changing in CMakelists.txt this line: set(EXTRA_LIBS -pthread libunitree_legged_sdk_arm64.so lcm) to 
set(EXTRA_LIBS -pthread libunitree_legged_sdk_amd64.so lcm)

**Comment by kenloumixx** [comment]
Hello,

Have you solved this problem? 

I am suffering from the same issue :-(

**Comment by Chen001117** [comment]
> Try changing in CMakelists.txt this line: set(EXTRA_LIBS -pthread libunitree_legged_sdk_arm64.so lcm) to set(EXTRA_LIBS -pthread libunitree_legged_sdk_amd64.so lcm)

This change fix my problem. Thanks!
