### ISSUE TITLE
Connecting A1 without Ethernet

### ISSUE THREAD

**Issue by staycoolish** [unitreerobotics/unitree_legged_sdk#43]
Hello,
I've seen this video: https://www.youtube.com/watch?v=wXFQqrSywTU
Here, the connection is made via WiFi, for Go1.
The same is valid for A1, right? Also, if connections with both ethernet and WiFi is possible, are there any differences between them?
Thank you,

**Comment by Wsser** [comment]
In this video it is shown that the robot is controlled through a wifi connection, but whether it is go1 or A1 we recommend using a network cable to connect to the robot so that there is no delay in controlling the robot and no errors are reported due to the ip address

**Comment by staycoolish** [comment]
Thanks
