### ISSUE TITLE
for Python 3.8 lib

### ISSUE THREAD

**Issue by devemin** [unitreerobotics/unitree_legged_sdk#46]
Dear Unitree

I tried the python commit, It works! (Python 3.7)

And I hope Could you add the ARM64 lib (.so)  for Python 3.8 ?
I need to use it with another host (Python3.8 / Ubuntu 20.04 / 64bit/ Raspi 4).

https://github.com/unitreerobotics/unitree_legged_sdk/tree/master/lib/python/arm64

Thanks :-)

**Comment by TrivasZhang** [comment]
Did [this lib](https://github.com/unitreerobotics/unitree_legged_sdk/tree/master/lib/python/arm64) unsatisfy your need?
Because this lib could work under raspbian buster, 64bit.

**Comment by devemin** [comment]
@TrivasZhang 
Thanks for you reply.

Maybe Is the lib file for python 3.7 ?

I think it can't use with python 3.8, right ?
I try it with raspi4 (ubuntu20.04/64bit/python 3.8 ), but It appeared the import error.

>>cd ./build
>>cmake ..
>>make -j4
>>//change the source, "sys.path.append('../lib/python/arm64')"
>>
>>export LD_LIBRARY_PATH=/path-to-unitree_legged_sdk/lib/cpp/arm64:$LD_LIBRARY_PATH
>>python3 ../example_py/example_walk.py
>>
>>ModuleNotFoundError: No module named 'robot_interface'



I need to use with python 3.8.

or, Should I install python 3.7 ?

**Comment by devemin** [comment]
fix

>>export LD_LIBRARY_PATH=/path-to-unitree_legged_sdk/lib/cpp/arm64:$LD_LIBRARY_PATH

>>export LD_LIBRARY_PATH=../lib/cpp/arm64:$LD_LIBRARY_PATH
![image](https://user-images.githubusercontent.com/52738228/176090466-94351a12-f7a2-4c7a-adbb-06b4dfdbc3d5.png)

**Comment by TrivasZhang** [comment]
So could this 3.7 version lib works with python3.8?
I know the 3.8 is more versatile, but the known issue is that many delivered robots are python 3.7.

**Comment by devemin** [comment]
No, It fix only the path string.
I tried, but It didn't work with python 3.8 yet. (It showed as screenshot.)

If unitree can provide the lib for python 3.8, It is convenient.
But If can't, I will try to add python 3.7.

Thank you, @TrivasZhang

**Comment by TrivasZhang** [comment]
I'll add 3.8.

**Comment by TrivasZhang** [comment]
> fix
> 
> > > export LD_LIBRARY_PATH=/path-to-unitree_legged_sdk/lib/cpp/arm64:$LD_LIBRARY_PATH
> 
> > > export LD_LIBRARY_PATH=../lib/cpp/arm64:$LD_LIBRARY_PATH
> 
> ![image](https://user-images.githubusercontent.com/52738228/176090620-5ad4162a-18ab-4b75-9d83-47a5be32c9d7.png)

Did absolute path not work?

**Comment by devemin** [comment]
I did again with absolute path, but same result.

( Off course Go1's raspi can work with this.)

![image](https://user-images.githubusercontent.com/52738228/176172611-c8554b7d-1ad2-40c3-8cd4-44c47add18ce.png)

**Comment by TrivasZhang** [comment]
`cd` to example_py folder then `python3 example_walk.py`

**Comment by devemin** [comment]
Thanks @littleggghost 
![image](https://user-images.githubusercontent.com/52738228/176174365-1e42dc37-1163-417c-9eaa-dc2cc3ed9003.png)

same

I think because of module version.

**Comment by TrivasZhang** [comment]
Use `sys.path.append('../lib/python/arm64')`
By the way, where did you find this raspi4 (ubuntu20.04/64bit/python 3.8 ) system image?

**Comment by devemin** [comment]
Next, I try to rename the lib.

```
mv ./robot_interface.cpython-37m-aarch64-linux-gnu.so robot_interface.so
```

Then version mismatch log appeared.

>>> import robot_interface
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: Python version mismatch: module was compiled for Python 3.7, but the interpreter version is incompatible: 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0].


![image](https://user-images.githubusercontent.com/52738228/176320911-43686a85-0e47-4935-95b8-ecae6dcddf14.png)


Thanks.

**Comment by TrivasZhang** [comment]
Please wait for the 3.8 version lib.

**Comment by devemin** [comment]
Dear TrivasZhang,

Thanks for helping me. I really appreciate it.
I will wait for it.

devemin

**Comment by TrivasZhang** [comment]
Good to hear that! If everything stable, I'll make a release.

**Comment by devemin** [comment]
I will use and test this for a week :-)

**Comment by Dorianproject** [comment]
Is there a python 3.10.6 solution for the: " No module named 'robot_interface' " problem 
?

**Comment by xyq1223** [comment]
Hello,we have provided the python_wrapper,please check and any version of Python （>3.0） can be used to control the robot dog
(https://github.com/unitreerobotics/unitree_legged_sdk/tree/go1/python_wrapper)

**Comment by ketulpanchal** [comment]
> Hello,we have provided the python_wrapper,please check and any version of Python （>3.0） can be used to control the robot dog (https://github.com/unitreerobotics/unitree_legged_sdk/tree/go1/python_wrapper)

Hi, I am using python3.10.12 and I am getting the same error saying "no module named robot_interface" Can I please know how to use python_wrapper to solve this error? Or do I need to use different version of Python
