### ISSUE TITLE
/unitree/state returns all zero values

### ISSUE THREAD

**Issue by kenloumixx** [unitreerobotics/unitree_legged_sdk#53]
Hello,

First of all, thank you for the robots and the software tools :)

I made a connection between unitree A1 robot and the laptop,

the rostopic lists appeared and ping test was successful.

However, when I ran 'rostopic echo /unitree/state/' that is supposed to show the joint positions and other things, all the parameter values returned zeros:
![all_zeros_2](https://user-images.githubusercontent.com/109455679/184153728-e83caa67-fdc1-4ade-a4df-392abfb2b1d1.png)

Is there anyone who faced this problem and solved it?

Thanks in advance!

**Comment by graiola** [comment]
Hello, how did you solve this issue? Thank you

**Comment by Charlescai123** [comment]
Hello, I'm also suffering from the issue and just wondering how you solved it, thanks!

**Comment by giuseppecialdella** [comment]
Hi, I have the same problem using the examples of the unitree_legged_sdk. 
When the robot is standing up in High Level and I try to print the HighState values it returns all zeros. 
How can i solve?
Moreover, what (which node or launch file of which repository) do i need to launch to obtain the topic /unitree/state in ROS? Thanks in advance!
