### ISSUE TITLE
Build failing - missing executables in CMakelists.txt

### ISSUE THREAD

**Issue by sarahnator** [unitreerobotics/unitree_legged_sdk#7]
Hi! I saw that lcm_server_high.cpp and lcm_server_low.cpp were recently removed from the examples directory, but these changes weren't propagated to the CMakelists.txt. Removing lines 30-35 (which specified these missing files)  in CMakelists.txt resolved the issue.

**Comment by Zhaiweiwei0** [comment]
Thank you, we've updated the CMakelists.txt.
