### ISSUE TITLE
Low Level Access to Sensors Raw Data

### ISSUE THREAD

**Issue by Kassra-sinaei** [unitreerobotics/unitree_legged_sdk#70]
What is the difference between q and q_raw in Motor_State structure? (The comments and documentation are vague, refer to comm.h line 70-80)
Is any kind of filtering applied to the IMU sensor readings (e.g LPF, HPF, or KF) If yes, is it possible to get the raw sensor readings with the SDK?

**Comment by xyq1223** [comment]
Hello,the gyroscope and accelerometer in the IMU structure are the raw data, while the quaternion and rpy are obtained by attitude algorithm.All variables with "_ raw "  in their name are reserved and their value is 0.
