### ISSUE TITLE
Multicast UDP GO1 EDU

### ISSUE THREAD

**Issue by Kulczar** [unitreerobotics/unitree_legged_sdk#93]
Hey guys, while the patrol robot i would like to connect and comand with udp connection, but i would like to know how to connect multicast in python code?

**Comment by xyq1223** [comment]
Hello, if you want to control multiple robot dogs at the same time, you can connect these robot dogs to your own wifi, so that each robot dog will be assigned its own ip address, and then control these ip addresses separately to achieve the goal
